spring:
  application:
    name: NetField-QAFormTestSet-Generator

langchain4j:
  open-ai:
    chat-model:
      api-key: ${AI_API_KEY}
      model-name: ${AI_MODEL_NAME}
      log-requests: ${AI_LOG_REQUESTS}
      log-responses: ${AI_LOG_RESPONSES}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
