spring:
  application:
    name: NetField-QAFormTestSet-Generator
  datasource:
    url: jdbc:mysql://localhost:3306/qa_generator?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启MyBatis Plus的SQL日志输出
    map-underscore-to-camel-case: true # 开启下划线到驼峰命名的映射

server:
  port: 8123
  servlet:
    context-path: /api

logging:
  level:
    dev.langchain4j: ${LANGCHAIN4J_LOG_LEVEL:debug}

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lbytech.QAGenerator.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${AI_API_KEY}
      model-name: ${AI_MODEL_NAME}
      log-requests: ${AI_LOG_REQUESTS}
      log-responses: ${AI_LOG_RESPONSES}
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${AI_API_KEY}
      model-name: ${AI_MODEL_NAME}
      log-requests: ${AI_LOG_REQUESTS}
      log-responses: ${AI_LOG_RESPONSES}

